# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace
      exclude: README.md
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
  - repo: https://github.com/fortran-lang/fprettify
    rev: v0.3.7
    hooks:
      - id: fprettify
        files: \.([fF]\d*|fypp)$
  - repo: https://github.com/pycqa/isort
    rev: 6.0.0
    hooks:
      - id: isort
        name: isort (python)
        additional_dependencies: [toml]
  # Black to format code with a consistent style
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black-jupyter
  #Validate our CITATION.cff
  - repo: https://github.com/citation-file-format/cff-converter-python
    rev: ebf0b5e44d67f8beaa1cd13a0d0393ea04c6058d
    hooks:
      - id: validate-cff
