name: C++ compiler info

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

outputs:
  cxx:
    description: "The default compiler that is available"
    value: ${{ steps.detect.outputs.cxx }}

runs:
  using: "composite"
  steps:
  - shell: bash -el {0}
    run: |
      # unset options -e
      set +e
      # Set to none, then we will create it...
      cxx=""
      names=(
        cxx
        g++
        clang++
        icpx
        nvc++
        icpc
      )
      for v in ${names[@]} ; do
        exe=$(which $v 2>/dev/null)
        printf '\n\n%-10s : %s\n' "$v" "$exe"
        if [ -e "$exe" ]; then
          "$exe" --version
          if [ -z "$cxx" ]; then
            cxx="$exe"
          fi
          if [ "${{ inputs.os }}" == "mac" ]; then
            otool -l "$exe"
          fi
        fi
      done
      echo "cxx='$cxx'" >> $GITHUB_OUTPUT

  - shell: bash -el {0}
    run: |
      echo CXX=$CXX
      echo CXXFLAGS=$CXXFLAGS

  - shell: bash -el {0}
    run: |
      # unset options -e
      set +e
      # CXX defined? Quick escape if that is the case...
      [ -z "$CXX" ] && exit 0
      DIR=$(dirname $(which $CXX))
      echo "Found CXX=$CXX in: $DIR"

      # Apparently windows find is extremely slow, we'll just
      # skip this information...
      if [ "${{ inputs.os }}" != "windows" ]; then
        echo "Other found g++ in same binary dir:"
        find $DIR -name "g++*"
        echo "Other found clang++ in same binary dir:"
        find $DIR -name "clang++*"
      fi
