name: Compiler info

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

runs:
  using: "composite"
  steps:
  - uses: ./.github/reuse_steps/print_c
    with:
      os: ${{ inputs.os }}
  - uses: ./.github/reuse_steps/print_cxx
    with:
      os: ${{ inputs.os }}
  - uses: ./.github/reuse_steps/print_fortran
    with:
      os: ${{ inputs.os }}
